### ISSUE TITLE
how to get this working?

### ISSUE THREAD

**Issue by iogitio** [k3erg/homebridge-marantz-denon-telnet#2]
are there instructions on how to get this working? Ideally I'd like to be able to change to the proper Input.

**Comment by siobhanellis** [comment]
Hello. I there anything we should see? I have loaded the plugin, and yet I do not see any devices in Homekit. I'm using a Denon AVR-X1500H.

**Comment by k3erg** [comment]
Looks like we have a problem with UPnP discovery.

**Comment by horstepipe** [comment]
yeah I'm be really interested in this plugin, too. How can we help?
I loaded the plugin successfully, but I'm seeing no corresponding devices in home kit

**Comment by k3erg** [comment]
Just fixed the missing node-arp package. VLC is finding my marantz, too – so the problem must be somewhere else.

**Comment by k3erg** [comment]
... and updated the discovery code to detect current firmware versions. Does that work for you @horstepipe, @siobhanellis ?

**Comment by horstepipe** [comment]
thanks it is working now!
But the only thing I can do is turn the AVR on and off. I hoped to be able to enable my quickselects with it. 
Do you plan to add more functionality?
Best regards

**Comment by k3erg** [comment]
Thanks for the feedback, so I close this issue.

Quickselect
Are these the four or somewhat buttons to select a predefined input, volume, and audiomode?

I've already prepared more commands, but I don't want to overload it. But I think quickselect would be a good thing to have. Please add a feature request and I see if I can implement it.

At the moment you have the following HomeKit controls:

When using the home app:
- Main Power ON/  OFF

When using the Eve app:
- Main Power: ON/  OFF
- every Zone: Mute ON /OFF
- every Zone: Volume

Fun thing is, that Elgatos Eve App supports more HomKit properties than Apples Home App. Good thing is: if you create automatizations in Eve, these run in Home, too. So I have a home cinema automatization, that runs curtains, light and power/volume on the AVR.

**Comment by siobhanellis** [comment]
I’ll get back to you.

I’m in UK at the moment, home at the weekend.

**Comment by siobhanellis** [comment]
I upgraded. I had to uninstall and install again. Still no amplifier . This is what I get:

server listening 0.0.0.0:65210
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Sun, 28 Oct 2018 22:20:11 GMT
EXT:
LOCATION: http://192.168.1.146:49152/wps_device.xml
SERVER: Unspecified, UPnP/1.0, Unspecified
ST: upnp:rootdevice
USN: uuid:6328ee00-c40c-47b5-9573-58ef6843499a::upnp:rootdevice


HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Sun, 28 Oct 2018 22:20:11 GMT
EXT:
LOCATION: http://192.168.1.146:49152/wps_device.xml
SERVER: Unspecified, UPnP/1.0, Unspecified
ST: upnp:rootdevice
USN: uuid:6328ee00-c40c-47b5-9573-58ef6843499a::upnp:rootdevice


HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Sun, 28 Oct 2018 22:20:11 GMT
EXT:
LOCATION: http://192.168.1.146:49152/wps_device.xml
SERVER: Unspecified, UPnP/1.0, Unspecified
ST: uuid:6328ee00-c40c-47b5-9573-58ef6843499a
USN: uuid:6328ee00-c40c-47b5-9573-58ef6843499a


HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Sun, 28 Oct 2018 22:20:11 GMT
EXT:
LOCATION: http://192.168.1.146:49152/wps_device.xml
SERVER: Unspecified, UPnP/1.0, Unspecified
ST: uuid:6328ee00-c40c-47b5-9573-58ef6843499a
USN: uuid:6328ee00-c40c-47b5-9573-58ef6843499a


HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Sun, 28 Oct 2018 22:20:11 GMT
EXT:
LOCATION: http://192.168.1.146:49152/wps_device.xml
SERVER: Unspecified, UPnP/1.0, Unspecified
ST: urn:schemas-wifialliance-org:device:WFADevice:1
USN: uuid:6328ee00-c40c-47b5-9573-58ef6843499a::urn:schemas-wifialliance-org:device:WFADevice:1


HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Sun, 28 Oct 2018 22:20:11 GMT
EXT:
LOCATION: http://192.168.1.146:49152/wps_device.xml
SERVER: Unspecified, UPnP/1.0, Unspecified
ST: urn:schemas-wifialliance-org:device:WFADevice:1
USN: uuid:6328ee00-c40c-47b5-9573-58ef6843499a::urn:schemas-wifialliance-org:device:WFADevice:1


HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Sun, 28 Oct 2018 22:20:11 GMT
EXT:
LOCATION: http://192.168.1.146:49152/wps_device.xml
SERVER: Unspecified, UPnP/1.0, Unspecified
ST: urn:schemas-wifialliance-org:service:WFAWLANConfig:1
USN: uuid:6328ee00-c40c-47b5-9573-58ef6843499a::urn:schemas-wifialliance-org:service:WFAWLANConfig:1


HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Sun, 28 Oct 2018 22:20:11 GMT
EXT:
LOCATION: http://192.168.1.146:49152/wps_device.xml
SERVER: Unspecified, UPnP/1.0, Unspecified
ST: urn:schemas-wifialliance-org:service:WFAWLANConfig:1
USN: uuid:6328ee00-c40c-47b5-9573-58ef6843499a::urn:schemas-wifialliance-org:service:WFAWLANConfig:1


HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1800
DATE: Sun, 28 Oct 2018 22:20:11 GMT
EXT:
LOCATION: http://192.168.1.1:49153/IGDdevicedesc.xml
OPT: "http://schemas.upnp.org/upnp/1/0/"; ns=01
01-NLS: 11ab74de-1dd2-11b2-91d3-e7243f3a86c3
SERVER: Linux/3.14.77, UPnP/1.0, Portable SDK for UPnP devices/1.6.19
X-User-Agent: redsonic
ST: upnp:rootdevice
USN: uuid:ebf5a0a0-1dd1-11b2-a90f-58ef68434e1a::upnp:rootdevice


[28/10/2018, 3:20:11 pm] [Broadlink RM] LR Fan Light getSwitchState: false
[28/10/2018, 3:20:11 pm] [Broadlink RM] LR Fan Light getBrightness: 100
[28/10/2018, 3:20:11 pm] [Broadlink RM] LR Fan getSwitchState: true
[28/10/2018, 3:20:11 pm] [Broadlink RM] LR Fan getFanSpeed: 25
[28/10/2018, 3:20:11 pm] [Broadlink RM] [INFO] Discovered Broadlink RM2 Pro Plus (272a) at 192.168.1.231 (34:ea:34:89:13:5a)
HTTP/1.1 200 OK
HOST: 239.255.255.250:1900
EXT:
CACHE-CONTROL: max-age=100
LOCATION: http://192.168.1.34:80/description.xml
SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.27.0
hue-bridgeid: 001788FFFE49C73E
ST: upnp:rootdevice
USN: uuid:2f402f80-da50-11e1-9b23-00178849c73e::upnp:rootdevice


HTTP/1.1 200 OK
HOST: 239.255.255.250:1900
EXT:
CACHE-CONTROL: max-age=100
LOCATION: http://192.168.1.34:80/description.xml
SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.27.0
hue-bridgeid: 001788FFFE49C73E
ST: uuid:2f402f80-da50-11e1-9b23-00178849c73e
USN: uuid:2f402f80-da50-11e1-9b23-00178849c73e


HTTP/1.1 200 OK
HOST: 239.255.255.250:1900
EXT:
CACHE-CONTROL: max-age=100
LOCATION: http://192.168.1.34:80/description.xml
SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.27.0
hue-bridgeid: 001788FFFE49C73E
ST: urn:schemas-upnp-org:device:basic:1
USN: uuid:2f402f80-da50-11e1-9b23-00178849c73e


HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Sun, 28 Oct 2018 22:20:12 GMT
EXT:
LOCATION: http://192.168.1.197:49152/wps_device.xml
SERVER: Unspecified, UPnP/1.0, Unspecified
ST: upnp:rootdevice
USN: uuid:0a88926c-4b56-4a62-8291-58ef68434e14::upnp:rootdevice


HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Sun, 28 Oct 2018 22:20:12 GMT
EXT:
LOCATION: http://192.168.1.197:49152/wps_device.xml
SERVER: Unspecified, UPnP/1.0, Unspecified
ST: upnp:rootdevice
USN: uuid:0a88926c-4b56-4a62-8291-58ef68434e14::upnp:rootdevice


HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Sun, 28 Oct 2018 22:20:12 GMT
EXT:
LOCATION: http://192.168.1.197:49152/wps_device.xml
SERVER: Unspecified, UPnP/1.0, Unspecified
ST: uuid:0a88926c-4b56-4a62-8291-58ef68434e14
USN: uuid:0a88926c-4b56-4a62-8291-58ef68434e14


HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Sun, 28 Oct 2018 22:20:12 GMT
EXT:
LOCATION: http://192.168.1.197:49152/wps_device.xml
SERVER: Unspecified, UPnP/1.0, Unspecified
ST: uuid:0a88926c-4b56-4a62-8291-58ef68434e14
USN: uuid:0a88926c-4b56-4a62-8291-58ef68434e14


HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Sun, 28 Oct 2018 22:20:12 GMT
EXT:
LOCATION: http://192.168.1.197:49152/wps_device.xml
SERVER: Unspecified, UPnP/1.0, Unspecified
ST: urn:schemas-wifialliance-org:device:WFADevice:1
USN: uuid:0a88926c-4b56-4a62-8291-58ef68434e14::urn:schemas-wifialliance-org:device:WFADevice:1


HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Sun, 28 Oct 2018 22:20:12 GMT
EXT:
LOCATION: http://192.168.1.197:49152/wps_device.xml
SERVER: Unspecified, UPnP/1.0, Unspecified
ST: urn:schemas-wifialliance-org:device:WFADevice:1
USN: uuid:0a88926c-4b56-4a62-8291-58ef68434e14::urn:schemas-wifialliance-org:device:WFADevice:1


HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Sun, 28 Oct 2018 22:20:12 GMT
EXT:
LOCATION: http://192.168.1.197:49152/wps_device.xml
SERVER: Unspecified, UPnP/1.0, Unspecified
ST: urn:schemas-wifialliance-org:service:WFAWLANConfig:1
USN: uuid:0a88926c-4b56-4a62-8291-58ef68434e14::urn:schemas-wifialliance-org:service:WFAWLANConfig:1


HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Sun, 28 Oct 2018 22:20:12 GMT
EXT:
LOCATION: http://192.168.1.197:49152/wps_device.xml
SERVER: Unspecified, UPnP/1.0, Unspecified
ST: urn:schemas-wifialliance-org:service:WFAWLANConfig:1
USN: uuid:0a88926c-4b56-4a62-8291-58ef68434e14::urn:schemas-wifialliance-org:service:WFAWLANConfig:1


HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Sun, 28 Oct 2018 22:20:12 GMT
EXT:
LOCATION: http://192.168.1.1:49152/wps_device.xml
SERVER: Unspecified, UPnP/1.0, Unspecified
ST: upnp:rootdevice
USN: uuid:4833a79d-40ae-43c0-b852-58ef68434e1a::upnp:rootdevice


HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Sun, 28 Oct 2018 22:20:12 GMT
EXT:
LOCATION: http://192.168.1.1:49152/wps_device.xml
SERVER: Unspecified, UPnP/1.0, Unspecified
ST: upnp:rootdevice
USN: uuid:4833a79d-40ae-43c0-b852-58ef68434e1a::upnp:rootdevice


HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Sun, 28 Oct 2018 22:20:12 GMT
EXT:
LOCATION: http://192.168.1.1:49152/wps_device.xml
SERVER: Unspecified, UPnP/1.0, Unspecified
ST: uuid:4833a79d-40ae-43c0-b852-58ef68434e1a
USN: uuid:4833a79d-40ae-43c0-b852-58ef68434e1a


HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Sun, 28 Oct 2018 22:20:12 GMT
EXT:
LOCATION: http://192.168.1.1:49152/wps_device.xml
SERVER: Unspecified, UPnP/1.0, Unspecified
ST: uuid:4833a79d-40ae-43c0-b852-58ef68434e1a
USN: uuid:4833a79d-40ae-43c0-b852-58ef68434e1a


HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Sun, 28 Oct 2018 22:20:12 GMT
EXT:
LOCATION: http://192.168.1.1:49152/wps_device.xml
SERVER: Unspecified, UPnP/1.0, Unspecified
ST: urn:schemas-wifialliance-org:device:WFADevice:1
USN: uuid:4833a79d-40ae-43c0-b852-58ef68434e1a::urn:schemas-wifialliance-org:device:WFADevice:1


HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Sun, 28 Oct 2018 22:20:12 GMT
EXT:
LOCATION: http://192.168.1.1:49152/wps_device.xml
SERVER: Unspecified, UPnP/1.0, Unspecified
ST: urn:schemas-wifialliance-org:device:WFADevice:1
USN: uuid:4833a79d-40ae-43c0-b852-58ef68434e1a::urn:schemas-wifialliance-org:device:WFADevice:1


HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Sun, 28 Oct 2018 22:20:12 GMT
EXT:
LOCATION: http://192.168.1.1:49152/wps_device.xml
SERVER: Unspecified, UPnP/1.0, Unspecified
ST: urn:schemas-wifialliance-org:service:WFAWLANConfig:1
USN: uuid:4833a79d-40ae-43c0-b852-58ef68434e1a::urn:schemas-wifialliance-org:service:WFAWLANConfig:1


HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Sun, 28 Oct 2018 22:20:12 GMT
EXT:
LOCATION: http://192.168.1.1:49152/wps_device.xml
SERVER: Unspecified, UPnP/1.0, Unspecified
ST: urn:schemas-wifialliance-org:service:WFAWLANConfig:1
USN: uuid:4833a79d-40ae-43c0-b852-58ef68434e1a::urn:schemas-wifialliance-org:service:WFAWLANConfig:1

HTTP/1.1 200 OK
HOST: 239.255.255.250:1900
EXT:
CACHE-CONTROL: max-age=100
LOCATION: http://192.168.1.34:80/description.xml
SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.27.0
hue-bridgeid: 001788FFFE49C73E
ST: upnp:rootdevice
USN: uuid:2f402f80-da50-11e1-9b23-00178849c73e::upnp:rootdevice


HTTP/1.1 200 OK
HOST: 239.255.255.250:1900
EXT:
CACHE-CONTROL: max-age=100
LOCATION: http://192.168.1.34:80/description.xml
SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.27.0
hue-bridgeid: 001788FFFE49C73E
ST: uuid:2f402f80-da50-11e1-9b23-00178849c73e
USN: uuid:2f402f80-da50-11e1-9b23-00178849c73e


HTTP/1.1 200 OK
HOST: 239.255.255.250:1900
EXT:
CACHE-CONTROL: max-age=100
LOCATION: http://192.168.1.34:80/description.xml
SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.27.0
hue-bridgeid: 001788FFFE49C73E
ST: urn:schemas-upnp-org:device:basic:1
USN: uuid:2f402f80-da50-11e1-9b23-00178849c73e
