### ISSUE TITLE
error loading plugin

### ISSUE THREAD

**Issue by siobhanellis** [k3erg/homebridge-marantz-denon-telnet#3]
Installed the module, but it errored until I manually added the npm module node-arp

[29/09/2018, 6:03:16 pm] ====================
[29/09/2018, 6:03:16 pm] ERROR LOADING PLUGIN homebridge-marantz-denon-telnet:
[29/09/2018, 6:03:16 pm] Error: Cannot find module 'node-arp'

**Comment by k3erg** [comment]
Txs. Will look into that.

**Comment by horstepipe** [comment]
same here, any workaround for it yet?

**Comment by horstepipe** [comment]
ah sorry I was stupid, just had to install node-arp via "npm install node-arp"
It's just not marked as a dependency in your code

**Comment by k3erg** [comment]
In: https://github.com/k3erg/marantz-denon-upnpdiscovery/commit/e63609c2540310d5861760de29515e5b1b0b2fda

**Comment by siobhanellis** [comment]
Sorry, How do I fix this? I installed node-arp.

Siobhan
