### ISSUE TITLE
Speaker accessory not supported

### ISSUE THREAD

**Issue by hmeerlo** [k3erg/homebridge-marantz-denon-telnet#9]
It seems to work fine, except that the home app says 'not supported' for the speaker accessories for both the MAIN zone and zone 2 (AVR-X1400H). So I'm not able to control the volume. Any idea what can be the problem?

**Comment by jeremyabramson** [comment]
I have the same issue with a Denon X1400 and Denon X4400.  The "switches" work to turn the units on or off, but the zone controls show up as "unsupported", and as best as I can tell, there's no other functionality other than on/off. =[

**Comment by k3erg** [comment]
The Speaker Accessory is fully specified and supported by the Homekit API, but Apples "Home" App is not exposing it, like may other accessories – thing is, the Speaker Accessory works in the background if it is part of an automation or scene. I guess they don't want to mix up Homekit and Air Play (2).

To access these not exposed, but supported accessory, you need to use an alternative app to program them like Elagatos excellent EVE app.

https://www.evehome.com/en/eve-app

BTW.
New features are coming (Smart Select). :)

**Comment by k3erg** [comment]
As this is only a Home App issue, I can't fix it on my end :)

**Comment by k3erg** [comment]
Note to self: but I will add it to the general description.
